### ISSUE TITLE
[Question] NitroPC 1 - Any coreboot updates planned?

### ISSUE THREAD

**Issue by cybacoffee** [Nitrokey/coreboot-builder#7]
Hi Nitrokey-Team,
thanks for your awesome work!  ❤️

Do you have any plans for updating coreboot (e.g. microcodes) for NitroPC 1 like [Librem](https://source.puri.sm/firmware/releases/-/blob/master/changelog.md) is doing that?

Thank you!

**Comment by daringer** [comment]
yes, there are plans, we are planning to do more formalized releases of this repository, once this is done, we'll also update the products with more recent coreboot versions

**Comment by cybacoffee** [comment]
Hi @daringer, thank you for the info and the insights!
